$schema: '1.0'
name: devbox
tasks:
  - name: choco
    parameters:
      package: kubernetes-cli
    description: Install kubectl
  - name: choco
    parameters:
      package: bruno
    description: Install Bruno
  - name: choco
    parameters:
      package: nodejs-lts
    description: Install nodejs
  - name: default-catalog/winget
    parameters:
      package: Microsoft.DotNet.SDK.8
    description: Install .NET 8
  - name: default-catalog/winget
    parameters:
      package: Microsoft.DotNet.SDK.6
    description: .NET 6
  - name: default-catalog/winget
    parameters:
      package: Microsoft.DotNet.Framework.DeveloperPack_4
      version: 4.6.2
    description: Install .NET Framework
  - name: default-catalog/winget
    parameters:
      package: Microsoft.VisualStudio.2022.Enterprise.Preview
    description: Install VS Enterprise
  - name: default-catalog/winget
    parameters:
      package: Microsoft.VisualStudioCode
    description: Install VS Code
  - name: default-catalog/winget
    parameters:
      package: Microsoft.AzureCLI
    description: Install Azure CLI
  - name: powershell
    parameters:
      command: Install-Module -Name Az -Repository PSGallery -Force
    description: Install Azure Powershell
  - name: powershell
    parameters:
      command: |
        $script = Invoke-RestMethod -Uri "https://aka.ms/install-artifacts-credprovider.ps1"
        iex $script
    description: Install Azure Artifacts Credential Provider
  - name: git-clone
    parameters:
      repositoryUrl: https://devdiv.visualstudio.com/DefaultCollection/OnlineServices/_git/azure-devcenter
      directory: C:\Repos
    description: Clone this repository into C:\Repos
  - name: install-vs-extension
    parameters:
      marketplaceItemName: SteveCadwallader.CodeMaidVS2022
    description: Install CodeMaid
  - name: install-vs-extension
    parameters:
      marketplaceItemName: vs-publisher-141975.SwitchStartupProjectForVS2022
    description: Install SwitchStartupProject
  - name: create-hyper-v-vm
    description: Create a Hyper-V Linux VM
